### ISSUE TITLE
git this demo, show errors:CocoaPods could not find compatible versions

### ISSUE THREAD

**Issue by UnknownWarning** [DJI-Mobile-SDK-Tutorials/iOS-UXSDKDemo#3]
##### What have been done:
1. git this demo from GitHub
2. do the `pod install`

##### Error occurs:
```shell
[!] CocoaPods could not find compatible versions for pod "DJI-UXSDK-iOS":
  In Podfile:
    DJI-UXSDK-iOS (~> 4.8.2)

None of your spec sources contain a spec satisfying the dependency: `DJI-UXSDK-iOS (~> 4.8.2)`.
```
##### Possible Reason
Does any one works on the same issue? If you know something, please give me a hint(thx)

**Comment by UnknownWarning** [comment]
#### Important
Hope people could see this notes: **This accout might not be offical.** 
Please double check the version of ux-sdk provided by [official site](https://developer.dji.com/ux-sdk/downloads/). By click the link, you will see the latest version of UX-SDK is **4.8.1**. (By the time: 4:20pm 12/28/2018, GMT+8)

**But** in this sample, the pod file pods `DJI-UXSDK-iOS (~> 4.8.2)`. 

**Are you serious???**

**Comment by dji-dev** [comment]
Hi @UnknownWarning , thanks for the feedbacks. We have updated the pod file and fix the version issue of ios uxsdk, it should be "4.8.1" now. Sorry for the inconvenience.
